services:
  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    ports:
      - "9000:9000"
    environment:
      # - ASR_MODEL=base
      - ASR_MODEL=turbo
      # - ASR_ENGINE=openai_whisper
      # - ASR_ENGINE=faster_whisper
      - ASR_ENGINE=whisperx
      - ASR_DEVICE=cuda
      - ASR_QUANTIZATION=float16
    runtime: nvidia
    volumes:
      - ./.docker_cache:/root/.cache
